baseURL = 'https://spikemurphy.github.io/BiochemProtocols/'
languageCode = 'en-us'
title = 'BiochemProtocols'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[security]
  enableInlineShortcodes = true

